# Generated by Django 2.1.1 on 2018-09-25 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SYS_local', models.PositiveSmallIntegerField(default=0)),
                ('SYS_Prioridad', models.CharField(choices=[('5', '5_Urgente'), ('4', '4_Alta'), ('3', '3_Media'), ('2', '2_Normal'), ('1', '1_Baja')], default='1', max_length=8)),
                ('SYS_EsActivo', models.BooleanField(default=True)),
                ('SYS_EsVisible', models.BooleanField(default=True)),
                ('SYS_EsOBSOLETO', models.BooleanField(default=False)),
                ('SYS_ESTADO', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Revisado', 'Revisado'), ('enRevision', 'enRevisión'), ('enEdicion', 'en Edición'), ('Inicial', 'Inicial')], default='Inicial', max_length=10)),
                ('SYS_lastESTADO', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Revisado', 'Revisado'), ('enRevision', 'enRevisión'), ('enEdicion', 'en Edición'), ('Inicial', 'Inicial')], default='Inicial', max_length=10)),
                ('SYS_Approver_Notes', models.CharField(blank=True, default='', max_length=250)),
                ('SYS_Reviser_Notes', models.CharField(blank=True, default='', max_length=250)),
                ('SYS_locked', models.BooleanField(blank=True, default=False)),
                ('SYS_lastModif_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('KIT', models.BooleanField(default=False)),
                ('numeroParte', models.CharField(default='ARA', max_length=15)),
                ('titulo', models.CharField(default='sin título', max_length=250)),
                ('unidad', models.CharField(choices=[('UN', 'UN'), (' M ', ' M '), ('KG ', 'KG '), ('LTS', 'LTS')], default='UN', max_length=4)),
                ('Descripcion', models.TextField(blank=True, default='', max_length=1500)),
                ('imagen_Pri_Nombre', models.CharField(blank=True, default='no_image.png', max_length=250)),
                ('imagen_pri', models.ImageField(blank=True, default='./no_image.png', upload_to='./pic_folder/')),
                ('marca', models.CharField(blank=True, default='', max_length=50)),
                ('modelo_NumParte', models.CharField(blank=True, default='', max_length=50)),
                ('linea', models.CharField(blank=True, default='', max_length=50)),
                ('comentario', models.CharField(blank=True, default='', max_length=50)),
                ('Reemplazable', models.BooleanField(blank=True, default=False)),
                ('Fab_a_Pedido', models.BooleanField(blank=True, default=False)),
                ('Plano', models.BooleanField(blank=True, default=False)),
                ('Ensayos', models.TextField(blank=True, default='', max_length=500)),
                ('Referencia1', models.CharField(blank=True, default='', max_length=250)),
                ('Referencia2', models.CharField(blank=True, default='', max_length=250)),
                ('Referencia3', models.CharField(blank=True, default='', max_length=250)),
                ('Referencia4', models.CharField(blank=True, default='', max_length=250)),
                ('Referencia5', models.CharField(blank=True, default='', max_length=250)),
                ('SYS_ApprovedByAuthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvers', to=settings.AUTH_USER_MODEL)),
                ('SYS_RevisedByAuthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisers', to=settings.AUTH_USER_MODEL)),
                ('SYS_dataEntryAuthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
