# Generated by Django 2.1.1 on 2018-09-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='SYS_local',
            field=models.BooleanField(default=False),
        ),
    ]
