# Generated by Django 2.1.1 on 2018-09-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0002_auto_20180925_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitNumSAP', models.CharField(default='', max_length=15)),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='articulo',
            name='SYS_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='partekit',
            field=models.ManyToManyField(help_text='Seleccione Articulos para este Kit', to='repuestos.Kit'),
        ),
    ]
