# Generated by Django 2.1.1 on 2018-09-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0003_auto_20180927_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=15)),
                ('cantidad_B', models.PositiveSmallIntegerField(default=0)),
                ('kitNumSAP_B', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repuestos.Articulo')),
            ],
        ),
    ]
