# Generated by Django 2.1.1 on 2018-09-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0004_kitb'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_C', models.CharField(max_length=200)),
                ('cantidad_C', models.PositiveSmallIntegerField(default=0)),
                ('kitNumSAP_C', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repuestos.Articulo')),
            ],
        ),
    ]
