# Generated by Django 2.1.1 on 2018-09-28 19:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0006_auto_20180927_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=False, verbose_name='Content'),
        ),
    ]
